import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./componets/auth/provider";
import SidebarWrapper from "./componets/ui/SidebarWrapper"; // Wrapper for Sidebar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          bg-[url('/images/wood.jpg')] bg-center bg-cover bg-fixed min-h-screen `}
      >
        <div className="flex flex-row scroll-smooth">
          {" "}
          <AuthProvider>
            <SidebarWrapper  />
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
