'use client';

import BarcodeScanner from '../componets/ui/BarcodeScanner'
import type { TextResult } from 'dynamsoft-javascript-barcode';
import Head from 'next/head'
import React from 'react';

export default function Home() {
  const [isActive,setIsActive] = React.useState(false);
  const [initialized,setInitialized] = React.useState(false);
  const license = process.env.DBRLicense || "";
  const toggleScanning = () => {
    setIsActive(!isActive);
  }

  const onScanned = (results:TextResult[]) => {
    if (results.length>0) {
      let text = "";
      for (let index = 0; index < results.length; index++) {
        const result = results[index];
        text = text + result.barcodeFormatString + ": " + result.barcodeText + "\n";
      }
      alert(text);
      setIsActive(false);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='w-screen h-screen bg-amber-800 '>
          <h2>Next.js Barcode Scanner</h2>
          {initialized ? (
            <button onClick={toggleScanning}>{isActive ? "Stop Scanning" : "Start Scanning"}</button>
          ) : (
            <div>Initializing...</div>
          )}
          <div className="barcodeScanner w-full h-full" >
            <BarcodeScanner
              license={license}
              onInitialized={() => setInitialized(true)}
              isActive={isActive}
              onScanned={(results) => onScanned(results)}
            ></BarcodeScanner>
          </div>
        </div>
      </main>
    </>
  )
}